pipeline {
    agent none
    
    stages {
        stage('Simulation') {
            parallel {
                stage('sim1') {
                    steps {
                        build job: 'load-one',
                         parameters: [
                            agentParameter(name: 'agentName', value: 'agent1')
                         ]
                    }
                }
                stage('sim2') {
                    steps {
                        build job: 'load-two',
                        parameters: [
                            agentParameter(name: 'agentName', value: 'agent2')
                        ]
                    }
                }
            }
        }
        
        stage('Downloading Reports') {
            steps {
                agent {label 'agent1'}
                cleanWs()
                git branch: 'master',
                    credentialsId: 'GitHubAcc',
                    url: 'https://github.com/dprymudrau/gatling-example.git'
                withCredentials([string(credentialsId: 'jcreds', variable: 'JENKINS_CREDS')]) {
                    sh "sbt -DjobNames=load-one,load-two -Djcreds=${JENKINS_CREDS} 'runMain com.solvd.example.util.JenkinsUtil'"
                }
            }
        }
        
        stage('Generating Report') {
            steps {
                agent {label 'agent1'}
                sh "sbt 'Gatling / generateReport'"
            }
            post {
               // Archive the log file.
               success {
                 archiveArtifacts 'target/gatling/**'
               }
            }
        }


    }
}