version: "3.9"
services:
    jagent1:
        build: "."
        container_name: "agent1"
        user: "root"
        environment: 
            JENKINS_URL: "http://192.168.88.248:8080"
            JENKINS_SECRET: "0fbb25bd5554de5585555243f0ad20086a58013b60bbfebc5d6397a11cb82372"
            JENKINS_AGENT_NAME: "agent1"
            JENKINS_AGENT_WORKDIR: "/var/jenkins_home"
        restart: "always"
        volumes: 
            - "$HOME/jnlp_agent1:/var/jenkins_home"

    jagent2:
        build: "."
        container_name: "agent2"
        user: "root"
        environment: 
            JENKINS_URL: "http://192.168.88.248:8080"
            JENKINS_SECRET: "de08ecb0388e29a27917f09bfa296fc22e875c6eb4b7fa68d5b3e61778be1ed6"
            JENKINS_AGENT_NAME: "agent2"
            JENKINS_AGENT_WORKDIR: "/var/jenkins_home"
        restart: "always"
        volumes: 
            - "$HOME/jnlp_agent2:/var/jenkins_home"