version: "3.9"
services:
    jagent1:
        build: "."
        container_name: "agent1"
        user: "root"
        environment: 
            JENKINS_URL: "http://192.168.88.248:8080"
            JENKINS_SECRET: "should be replaced"
            JENKINS_AGENT_NAME: "agent1"
            JENKINS_AGENT_WORKDIR: "/var/jenkins_home"
        restart: "always"
        volumes: 
            - "$HOME/jnlp_agent1:/var/jenkins_home"

    jagent2:
        build: "."
        container_name: "agent2"
        user: "root"
        environment: 
            JENKINS_URL: "http://192.168.88.248:8080"
            JENKINS_SECRET: "should be replaced"
            JENKINS_AGENT_NAME: "agent2"
            JENKINS_AGENT_WORKDIR: "/var/jenkins_home"
        restart: "always"
        volumes: 
            - "$HOME/jnlp_agent2:/var/jenkins_home"