version: "3.9"
services:
    jagent1:
        build: "."
        container_name: "agent1"
        user: "root"
        environment: 
            JENKINS_URL: "http://192.168.0.16:8080"
            JENKINS_SECRET: "7873ddafaf62263f3d753c19015b54825e765f997a10c78cba6a56f69fb2c73f"
            JENKINS_AGENT_NAME: "agent1"
            JENKINS_AGENT_WORKDIR: "/var/jenkins_home"
        restart: "always"
        volumes: 
            - "$HOME/jnlp_agent1:/var/jenkins_home"

    jagent2:
        build: "."
        container_name: "agent2"
        user: "root"
        environment: 
            JENKINS_URL: "http://192.168.0.16:8080"
            JENKINS_SECRET: "1f9fe857972b6d16f9b9496dc569d5fbf303a96155e29707b8b1c59f212628a6"
            JENKINS_AGENT_NAME: "agent2"
            JENKINS_AGENT_WORKDIR: "/var/jenkins_home"
        restart: "always"
        volumes: 
            - "$HOME/jnlp_agent2:/var/jenkins_home"