pipeline {
    agent none

    parameters {
        string(name: 'agentName', defaultValue: 'agent1', description: 'Agent')
      }
    
    options {
        ansiColor('xterm')
    }

    stages {
        stage('Build') {
            agent {label '${agentName}'}
            steps {
                // Get some code from a GitHub repository
                git branch: 'master',
                    credentialsId: 'GitHubAcc',
                    url: 'https://github.com/dprymudrau/gatling-example.git'

                // Run Simulation on a Unix agent.
                withCredentials([
                    string(credentialsId: 'baseUrl', variable: 'BASE_URL'),
                    string(credentialsId: 'crypt', variable: 'CRYPT')
                    ]) {
                    sh "sbt -DbaseUrl=$BASE_URL -Dcrypt=$CRYPT 'Gatling / testOnly com.solvd.example.simulation.Simulation'"
                }

            }

            post {
                // Archive the log file.
                success {
                    archiveArtifacts 'target/gatling/**'
                }
            }
        }
    }
}
